local colors = {
  bg            = "#000000",
  fg            = "#8f93a2",
  white         = "#ffffff",
  black         = "#000000",
  light_grey    = "#464b5d",
  alt_fg        = "#eeffff",
  alt_bg        = "#0f111a",
  comment       = "#FF1493",
  pink          = "#eb54f7",
  red           = "#FF3B3B",
  green         = "#7FFF00",
  yellow        = "#FFFF00",
  yellow_orange = "#FFB648",
  blue          = "#0077FF",
  purple        = "#bb77ff",
  error         = "#ff5370",
  warn          = "#ffcb6b",
  info          = "#c3e88d",
  hint          = "#82aaff",
  error_bg      = "#ff5370",
  warn_bg       = "#ffcb6b",
  info_bg       = "#c3e88d",
  hint_bg       = "#82aaff",
  popup_fg      = "#00ffff",
  cyan          = "#75fbfd",
  cursor_fg     = "#ffcc00",
  cursor_bg     = "#000000",
  selection     = "#52597550",
  sign_add      = "#c3e88d",
  sign_change   = "#82aaff",
  sign_delete   = "#ff5370",
  line          = "#1D1F27",
  light_cyan    = "#5face3"

}
return colors
